### ISSUE TITLE
Unable to run, needs package errors (not available for python 3) using your 'pSearch = PyGle(query="test")'

### ISSUE THREAD

**Issue by Larz60p** [Javinator9889/pyGle#1]
**Describe the bug**

**To Reproduce**

from pprint import pprint  # Not necessary but for a beautiful print
from pyGle import PyGle

pSearch = PyGle(query="test")
ft = pSearch.doSearch()  # A Future object
pprint(ft.result())

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Javinator9889** [comment]
Hi, it works for me perfectly.

Please, **revise you code** and *submit the full exception* @Larz60p 
Also please provide the information that is **described at** the *issues template*.

---------

![image](https://user-images.githubusercontent.com/25952165/44921118-f209ad00-ad41-11e8-8622-3ea590cc742e.png)

**Comment by Javinator9889** [comment]
No more info provided - closed
